-- Convert osm to intermediate schema
-- author: SteSad

SCHEMA_NAME = 'inter'

-- A place to store the SQL tables we will define shortly.
local tables = {}

-- Creates a table with the information when the schema was created
-- only create, must insert with postscripted sql
tables.creationinformation = osm2pgsql.define_table({
    name = 'creationinformation',
    columns = {
        { column = 'id', sql_type = 'bigserial', create_only = true },
        { column = 'timestampstring', type = 'text' }
    },
    schema = SCHEMA_NAME
})

-- Create table to store all nodes
tables.nodes = osm2pgsql.define_table({
    name = 'nodes',
    ids = { type = 'node', id_column = 'osm_id' },
    columns = {
        { column = 'id', sql_type = 'bigserial', create_only = true },
        { column = 'tstamp', sql_type = 'timestamp' },
        { column = 'mapfeatures_ids', type = 'text' },
        { column = 'serializedtags', type = 'hstore' },
        { column = 'geom', type = 'point', projection = 4326 },
        { column = 'uid', type = 'text' },
        { column = 'username', type = 'text' },
        { column = 'name', type = 'text' },
        { column = 'url', type = 'text' },
        { column = 'geom_changed', type = 'bool' },
        { column = 'object_changed', type = 'bool' },
        { column = 'deleted', type = 'bool' },
        { column = 'object_new', type = 'bool' },
        { column = 'has_name', type = 'bool' },
        { column = 'valid', type = 'bool' }
    },
    schema = SCHEMA_NAME
})

-- Create waynodes
tables.waynodes = osm2pgsql.define_table({
    name = 'waynodes',
    columns = {
        { column = 'id', sql_type = 'bigserial', create_only = true },
        { column = 'way_id', type = 'bigint' },
        { column = 'node_id', type = 'bigint' },
    },
    schema = SCHEMA_NAME
})

-- Create table to store all ways
tables.ways = osm2pgsql.define_table({
    name = 'ways',
    ids = { type = 'way', id_column = 'osm_id' },
    columns = {
        { column = 'id', sql_type = 'bigserial', create_only = true },
        { column = 'tstamp', sql_type = 'timestamp' },
        { column = 'mapfeatures_ids', type = 'text' },
        { column = 'serializedtags', type = 'hstore' },
        { column = 'geom', type = 'linestring', projection = 4326 },
        { column = 'uid', type = 'text' },
        { column = 'username', type = 'text' },
        { column = 'name', type = 'text' },
        { column = 'url', type = 'text' },
        { column = 'geom_changed', type = 'bool' },
        { column = 'object_changed', type = 'bool' },
        { column = 'deleted', type = 'bool' },
        { column = 'object_new', type = 'bool' },
        { column = 'has_name', type = 'bool' },
        { column = 'valid', type = 'bool' }
    },
    schema = SCHEMA_NAME
})

--relationmembers
tables.relationmembers = osm2pgsql.define_table({
    name = 'relationmembers',
    columns = {
        { column = 'id', sql_type = 'bigserial', create_only = true },
        { column = 'relation_id', type = 'bigint' },
        { column = 'node_id', type = 'bigint' },
        { column = 'way_id', type = 'bigint' },
        { column = 'member_rel_id', type = 'bigint' },
        { column = 'role', type = 'text' },

    },
    schema = SCHEMA_NAME
})

-- Create table to store all relations
tables.relations = osm2pgsql.define_table({
    name = 'relations',
    ids = { type = 'relation', id_column = 'osm_id' },
    columns = {
        { column = 'id', sql_type = 'bigserial', create_only = true },
        { column = 'tstamp', sql_type = 'timestamp' },
        { column = 'mapfeatures_ids', type = 'text' },
        { column = 'serializedtags', type = 'hstore' },
        { column = 'geom', type = 'geometry', projection = 4326 },
        { column = 'uid', type = 'text' },
        { column = 'username', type = 'text' },
        { column = 'name', type = 'text' },
        { column = 'url', type = 'text' },
        { column = 'geom_changed', type = 'bool' },
        { column = 'object_changed', type = 'bool' },
        { column = 'deleted', type = 'bool' },
        { column = 'object_new', type = 'bool' },
        { column = 'has_name', type = 'bool' },
        { column = 'valid', type = 'bool' }
    },
    schema = SCHEMA_NAME
})




-- Debug output: Show definition of tables
print("Create tables:")
for name, dtable in pairs(tables) do
    print("\t" .. name)
end

-- Helper function to remove some of the tags we usually are not interested in.
-- Returns true if there are no tags left.
local function clean_tags(tags)
    tags.odbl = nil
    tags.created_by = nil
    tags.source = nil
    tags['source:ref'] = nil

    return next(tags) == nil
end


-- table to define all columns, there map features
local classifications = {
    -- Admin Level
    [0]={['key']='admin_level', ['value']='undefined'},
    {['key']='admin_level', ['value']='1'},
    {['key']='admin_level', ['value']='2'},
    {['key']='admin_level', ['value']='3'},
    {['key']='admin_level', ['value']='4'},
    {['key']='admin_level', ['value']='5'},
    {['key']='admin_level', ['value']='6'},
    {['key']='admin_level', ['value']='7'},
    {['key']='admin_level', ['value']='8'},
    {['key']='admin_level', ['value']='9'},
    {['key']='admin_level', ['value']='10'},
    {['key']='admin_level', ['value']='11'},
    {['key']='admin_level', ['value']='12'},

    -- Aerialway
    {['key']='aerialway', ['value']='undefined'},
    {['key']='aerialway', ['value']='cable_car'},
    {['key']='aerialway', ['value']='gondola'},
    {['key']='aerialway', ['value']='mixed_lift'},
    {['key']='aerialway', ['value']='chair_lift'},
    {['key']='aerialway', ['value']='drag_lift'},
    {['key']='aerialway', ['value']='t-bar'},
    {['key']='aerialway', ['value']='j-bar'},
    {['key']='aerialway', ['value']='platter'},
    {['key']='aerialway', ['value']='rope_tow'},
    {['key']='aerialway', ['value']='magic_carpet'},
    {['key']='aerialway', ['value']='zip_line'},
    {['key']='aerialway', ['value']='goods'},
    {['key']='aerialway', ['value']='pylon'},
    {['key']='aerialway', ['value']='station'},
    {['key']='aerialway', ['value']='canopy'},

    -- Aeroway
    {['key']='aeroway', ['value']='undefined'},
    {['key']='aeroway', ['value']='aerodrome'},
    {['key']='aeroway', ['value']='apron'},
    {['key']='aeroway', ['value']='gate'},
    {['key']='aeroway', ['value']='hangar'},
    {['key']='aeroway', ['value']='helipad'},
    {['key']='aeroway', ['value']='heliport'},
    {['key']='aeroway', ['value']='navigationaid'},
    {['key']='aeroway', ['value']='runway'},
    {['key']='aeroway', ['value']='spaceport'},
    {['key']='aeroway', ['value']='taxilane'},
    {['key']='aeroway', ['value']='taxiway'},
    {['key']='aeroway', ['value']='terminal'},
    {['key']='aeroway', ['value']='windsock'},
    -- Amenity
    {['key']='amenity', ['value']='undefined'},
    {['key']='amenity', ['value']='bar'},
    {['key']='amenity', ['value']='biergarten'},
    {['key']='amenity', ['value']='cafe'},
    {['key']='amenity', ['value']='fast_food'},
    {['key']='amenity', ['value']='food_court'},
    {['key']='amenity', ['value']='ice_cream'},
    {['key']='amenity', ['value']='pub'},
    {['key']='amenity', ['value']='restaurant'},
    {['key']='amenity', ['value']='college'},
    {['key']='amenity', ['value']='driving_school'},
    {['key']='amenity', ['value']='kindergarten'},
    {['key']='amenity', ['value']='language_school'},
    {['key']='amenity', ['value']='library'},
    {['key']='amenity', ['value']='toy_library'},
    {['key']='amenity', ['value']='music_school'},
    {['key']='amenity', ['value']='school'},
    {['key']='amenity', ['value']='university'},
    {['key']='amenity', ['value']='bicycle_parking'},
    {['key']='amenity', ['value']='bicycle_repair_station'},
    {['key']='amenity', ['value']='biycycle_rental'},
    {['key']='amenity', ['value']='boat_rental'},
    {['key']='amenity', ['value']='boat_sharing'},
    {['key']='amenity', ['value']='bus_station'},
    {['key']='amenity', ['value']='car_rental'},
    {['key']='amenity', ['value']='car_sharing'},
    {['key']='amenity', ['value']='car_wash'},
    {['key']='amenity', ['value']='vehicle_inspection'},
    {['key']='amenity', ['value']='charging_station'},
    {['key']='amenity', ['value']='ferry_terminal'},
    {['key']='amenity', ['value']='fuel'},
    {['key']='amenity', ['value']='grit_bin'},
    {['key']='amenity', ['value']='motorcycle_parking'},
    {['key']='amenity', ['value']='parking'},
    {['key']='amenity', ['value']='parking_entrance'},
    {['key']='amenity', ['value']='parking_space'},
    {['key']='amenity', ['value']='taxi'},
    {['key']='amenity', ['value']='atm'},
    {['key']='amenity', ['value']='bank'},
    {['key']='amenity', ['value']='bureau_de_change'},
    {['key']='amenity', ['value']='baby_hatch'},
    {['key']='amenity', ['value']='clinic'},
    {['key']='amenity', ['value']='dentist'},
    {['key']='amenity', ['value']='doctors'},
    {['key']='amenity', ['value']='hospital'},
    {['key']='amenity', ['value']='nursing_home'},
    {['key']='amenity', ['value']='pharmacy'},
    {['key']='amenity', ['value']='social_facility'},
    {['key']='amenity', ['value']='veterinary'},
    {['key']='amenity', ['value']='arts_centre'},
    {['key']='amenity', ['value']='brothel'},
    {['key']='amenity', ['value']='casino'},
    {['key']='amenity', ['value']='cinema'},
    {['key']='amenity', ['value']='community_centre'},
    {['key']='amenity', ['value']='conference_centre'},
    {['key']='amenity', ['value']='events_venue'},
    {['key']='amenity', ['value']='fountain'},
    {['key']='amenity', ['value']='gambling'},
    {['key']='amenity', ['value']='love_hotel'},
    {['key']='amenity', ['value']='nightclub'},
    {['key']='amenity', ['value']='planetarium'},
    {['key']='amenity', ['value']='public_bookcase'},
    {['key']='amenity', ['value']='social_centre'},
    {['key']='amenity', ['value']='stripclub'},
    {['key']='amenity', ['value']='studio'},
    {['key']='amenity', ['value']='swingerclub'},
    {['key']='amenity', ['value']='theatre'},
    {['key']='amenity', ['value']='courthouse'},
    {['key']='amenity', ['value']='fire_station'},
    {['key']='amenity', ['value']='police'},
    {['key']='amenity', ['value']='post_box'},
    {['key']='amenity', ['value']='post_depot'},
    {['key']='amenity', ['value']='post_office'},
    {['key']='amenity', ['value']='prison'},
    {['key']='amenity', ['value']='ranger_station'},
    {['key']='amenity', ['value']='townhall'},
    {['key']='amenity', ['value']='bbq'},
    {['key']='amenity', ['value']='bench'},
    {['key']='amenity', ['value']='dog_toilet'},
    {['key']='amenity', ['value']='drinking_water'},
    {['key']='amenity', ['value']='give_box'},
    {['key']='amenity', ['value']='parcel_locker'},
    {['key']='amenity', ['value']='shelter'},
    {['key']='amenity', ['value']='shower'},
    {['key']='amenity', ['value']='telephone'},
    {['key']='amenity', ['value']='toilets'},
    {['key']='amenity', ['value']='water_point'},
    {['key']='amenity', ['value']='watering_place'},
    {['key']='amenity', ['value']='sanitary_dump_station'},
    {['key']='amenity', ['value']='recycling'},
    {['key']='amenity', ['value']='waste_basket'},
    {['key']='amenity', ['value']='waste_disposal'},
    {['key']='amenity', ['value']='waste_transfer_station'},
    {['key']='amenity', ['value']='animal_boarding'},
    {['key']='amenity', ['value']='animal_breeding'},
    {['key']='amenity', ['value']='animal_shelter'},
    {['key']='amenity', ['value']='baking_oven'},
    {['key']='amenity', ['value']='childcare'},
    {['key']='amenity', ['value']='clock'},
    {['key']='amenity', ['value']='crematorium'},
    {['key']='amenity', ['value']='dive_centre'},
    {['key']='amenity', ['value']='funeral_hall'},
    {['key']='amenity', ['value']='grave_yard'},
    {['key']='amenity', ['value']='hunting_stand'},
    {['key']='amenity', ['value']='internet_cafe'},
    {['key']='amenity', ['value']='kitchen'},
    {['key']='amenity', ['value']='kneipp_water_cure'},
    {['key']='amenity', ['value']='lounger'},
    {['key']='amenity', ['value']='marketplace'},
    {['key']='amenity', ['value']='monastery'},
    {['key']='amenity', ['value']='photo_booth'},
    {['key']='amenity', ['value']='place_of_mourning'},
    {['key']='amenity', ['value']='place_of_worship'},
    {['key']='amenity', ['value']='public_bath'},
    {['key']='amenity', ['value']='refugee_site'},
    {['key']='amenity', ['value']='vending_machine'},
    -- {['key']='amenity', ['value']='embassy'}, -- use office=diplomatic
    -- Barrier
    {['key']='barrier', ['value']='undefined'},
    {['key']='barrier', ['value']='cable_barrier'},
    {['key']='barrier', ['value']='city_wall'},
    {['key']='barrier', ['value']='ditch'},
    {['key']='barrier', ['value']='fence'},
    {['key']='barrier', ['value']='guard_rail'},
    {['key']='barrier', ['value']='handrail'},
    {['key']='barrier', ['value']='hedge'},
    {['key']='barrier', ['value']='kerb'},
    {['key']='barrier', ['value']='retaining_wall'},
    {['key']='barrier', ['value']='wall'},
    {['key']='barrier', ['value']='block'},
    {['key']='barrier', ['value']='bollard'},
    {['key']='barrier', ['value']='border_control'},
    {['key']='barrier', ['value']='bump_gate'},
    {['key']='barrier', ['value']='bus_trap'},
    {['key']='barrier', ['value']='cattle_grid'},
    {['key']='barrier', ['value']='chain'},
    {['key']='barrier', ['value']='cycle_barrier'},
    {['key']='barrier', ['value']='debris'},
    {['key']='barrier', ['value']='entrance'},
    {['key']='barrier', ['value']='full-height_turnstile'},
    {['key']='barrier', ['value']='gate'},
    {['key']='barrier', ['value']='hampshire_gate'},
    {['key']='barrier', ['value']='height_restrictor'},
    {['key']='barrier', ['value']='horse_stile'},
    {['key']='barrier', ['value']='jersey_barrier'},
    {['key']='barrier', ['value']='kissing_gate'},
    {['key']='barrier', ['value']='lift_gate'},
    {['key']='barrier', ['value']='log'},
    {['key']='barrier', ['value']='motorcycle_barrier'},
    {['key']='barrier', ['value']='rope'},
    {['key']='barrier', ['value']='sally_port'},
    {['key']='barrier', ['value']='spikes'},
    {['key']='barrier', ['value']='stile'},
    {['key']='barrier', ['value']='sump_buster'},
    {['key']='barrier', ['value']='swing_gate'},
    {['key']='barrier', ['value']='toll_booth'},
    {['key']='barrier', ['value']='turnstile'},
    {['key']='barrier', ['value']='yes'},
    -- Boundary
    {['key']='boundary', ['value']='undefined'},
    {['key']='boundary', ['value']='aboriginal_lands'},
    {['key']='boundary', ['value']='administrative'},
    {['key']='boundary', ['value']='border_zone'},
    {['key']='boundary', ['value']='forest'},
    {['key']='boundary', ['value']='forest_compartment'},
    {['key']='boundary', ['value']='hazard'},
    {['key']='boundary', ['value']='maritime'},
    {['key']='boundary', ['value']='marker'},
    {['key']='boundary', ['value']='national_park'},
    {['key']='boundary', ['value']='place'},
    {['key']='boundary', ['value']='political'},
    {['key']='boundary', ['value']='postal_code'},
    {['key']='boundary', ['value']='protected_area'},
    {['key']='boundary', ['value']='special_economic_zone'},
    {['key']='boundary', ['value']='disputed'},
    {['key']='boundary', ['value']='historic'},
    -- Building
    {['key']='building', ['value']='undefined'},
    {['key']='building', ['value']='apartments'},
    {['key']='building', ['value']='bungalow'},
    {['key']='building', ['value']='cabin'},
    {['key']='building', ['value']='detached'},
    {['key']='building', ['value']='dormitory'},
    {['key']='building', ['value']='farm'},
    {['key']='building', ['value']='ger'},
    {['key']='building', ['value']='hotel'},
    {['key']='building', ['value']='house'},
    {['key']='building', ['value']='houseboat'},
    {['key']='building', ['value']='residential'},
    {['key']='building', ['value']='semidetached_house'},
    {['key']='building', ['value']='static_caravan'},
    {['key']='building', ['value']='terrace'},
    {['key']='building', ['value']='commercial'},
    {['key']='building', ['value']='industrial'},
    {['key']='building', ['value']='kiosk'},
    {['key']='building', ['value']='office'},
    {['key']='building', ['value']='retail'},
    {['key']='building', ['value']='supermarket'},
    {['key']='building', ['value']='warehouse'},
    {['key']='building', ['value']='cathedral'},
    {['key']='building', ['value']='chapel'},
    {['key']='building', ['value']='church'},
    {['key']='building', ['value']='kingdom_hall'},
    {['key']='building', ['value']='monastery'},
    {['key']='building', ['value']='mosque'},
    {['key']='building', ['value']='presbytery'},
    {['key']='building', ['value']='religious'},
    {['key']='building', ['value']='shrine'},
    {['key']='building', ['value']='synagogue'},
    {['key']='building', ['value']='temple'},
    {['key']='building', ['value']='bakehouse'},
    {['key']='building', ['value']='civic'},
    {['key']='building', ['value']='fire_station'},
    {['key']='building', ['value']='government'},
    {['key']='building', ['value']='hospital'},
    {['key']='building', ['value']='kindergarten'},
    {['key']='building', ['value']='public'},
    {['key']='building', ['value']='school'},
    {['key']='building', ['value']='toilets'},
    {['key']='building', ['value']='train_station'},
    {['key']='building', ['value']='transportation'},
    {['key']='building', ['value']='university'},
    {['key']='building', ['value']='barn'},
    {['key']='building', ['value']='conservatory'},
    {['key']='building', ['value']='cowshed'},
    {['key']='building', ['value']='farm_auxiliary'},
    {['key']='building', ['value']='greenhouse'},
    {['key']='building', ['value']='slurry_tank'},
    {['key']='building', ['value']='stable'},
    {['key']='building', ['value']='sty'},
    {['key']='building', ['value']='grandstand'},
    {['key']='building', ['value']='pavilion'},
    {['key']='building', ['value']='riding_hall'},
    {['key']='building', ['value']='sports_hall'},
    {['key']='building', ['value']='stadium'},
    {['key']='building', ['value']='hangar'},
    {['key']='building', ['value']='hut'},
    {['key']='building', ['value']='shed'},
    {['key']='building', ['value']='carport'},
    {['key']='building', ['value']='garage'},
    {['key']='building', ['value']='garages'},
    {['key']='building', ['value']='parking'},
    {['key']='building', ['value']='digester'},
    {['key']='building', ['value']='service'},
    {['key']='building', ['value']='transformer_tower'},
    {['key']='building', ['value']='water_tower'},
    {['key']='building', ['value']='beach_hut'},
    {['key']='building', ['value']='bunker'},
    {['key']='building', ['value']='bridge'},
    {['key']='building', ['value']='castle'},
    {['key']='building', ['value']='construction'},
    {['key']='building', ['value']='container'},
    {['key']='building', ['value']='gatehouse'},
    {['key']='building', ['value']='roof'},
    {['key']='building', ['value']='ruins'},
    {['key']='building', ['value']='tent'},
    {['key']='building', ['value']='tree_house'},
    {['key']='building', ['value']='yes'},
    -- Craft
    {['key']='craft', ['value']='undefined'},
    {['key']='craft', ['value']='agricultural_engines'},
    {['key']='craft', ['value']='atelier'},
    {['key']='craft', ['value']='bakery'},
    {['key']='craft', ['value']='basket_maker'},
    {['key']='craft', ['value']='beekeeper'},
    {['key']='craft', ['value']='blacksmith'},
    {['key']='craft', ['value']='boatbuilder'},
    {['key']='craft', ['value']='bookbinder'},
    {['key']='craft', ['value']='brewery'},
    {['key']='craft', ['value']='builder'},
    {['key']='craft', ['value']='cabinet_maker'},
    {['key']='craft', ['value']='car_painter'},
    {['key']='craft', ['value']='carpenter'},
    {['key']='craft', ['value']='carpet_layer'},
    {['key']='craft', ['value']='caterer'},
    {['key']='craft', ['value']='chimney_sweeper'},
    {['key']='craft', ['value']='cleaning'},
    {['key']='craft', ['value']='clockmaker'},
    {['key']='craft', ['value']='confectionery'},
    {['key']='craft', ['value']='cooper'},
    {['key']='craft', ['value']='dental_technician'},
    {['key']='craft', ['value']='distillery'},
    {['key']='craft', ['value']='door_construction'},
    {['key']='craft', ['value']='dressmaker'},
    {['key']='craft', ['value']='electronics_repair'},
    {['key']='craft', ['value']='embroiderer'},
    {['key']='craft', ['value']='electrician'},
    {['key']='craft', ['value']='engraver'},
    {['key']='craft', ['value']='floorer'},
    {['key']='craft', ['value']='gardener'},
    {['key']='craft', ['value']='glaziery'},
    {['key']='craft', ['value']='goldsmith'},
    {['key']='craft', ['value']='grinding_mill'},
    {['key']='craft', ['value']='handicraft'},
    {['key']='craft', ['value']='hvac'},
    {['key']='craft', ['value']='insulation'},
    {['key']='craft', ['value']='interior_work'},
    {['key']='craft', ['value']='jeweller'},
    {['key']='craft', ['value']='joiner'},
    {['key']='craft', ['value']='key_cutter'},
    {['key']='craft', ['value']='locksmith'},
    {['key']='craft', ['value']='metal_construction'},
    {['key']='craft', ['value']='mint'},
    {['key']='craft', ['value']='musical_instrument'},
    {['key']='craft', ['value']='oil_mill'},
    {['key']='craft', ['value']='optician'},
    {['key']='craft', ['value']='organ_builder'},
    {['key']='craft', ['value']='painter'},
    {['key']='craft', ['value']='parquet_layer'},
    {['key']='craft', ['value']='photographer'},
    {['key']='craft', ['value']='photographic_laboratory'},
    {['key']='craft', ['value']='piano_tuner'},
    {['key']='craft', ['value']='plasterer'},
    {['key']='craft', ['value']='plumber'},
    {['key']='craft', ['value']='pottery'},
    {['key']='craft', ['value']='printer'},
    {['key']='craft', ['value']='printmaker'},
    {['key']='craft', ['value']='rigger'},
    {['key']='craft', ['value']='roofer'},
    {['key']='craft', ['value']='saddler'},
    {['key']='craft', ['value']='sailmaker'},
    {['key']='craft', ['value']='sawmill'},
    {['key']='craft', ['value']='scaffolder'},
    {['key']='craft', ['value']='shoemaker'},
    {['key']='craft', ['value']='sculptor'},
    {['key']='craft', ['value']='signmaker'},
    {['key']='craft', ['value']='stand_builder'},
    {['key']='craft', ['value']='stonemason'},
    {['key']='craft', ['value']='stove_fitter'},
    {['key']='craft', ['value']='sun_protection'},
    {['key']='craft', ['value']='tailor'},
    {['key']='craft', ['value']='tiler'},
    {['key']='craft', ['value']='tinsmith'},
    {['key']='craft', ['value']='toolmaker'},
    {['key']='craft', ['value']='turner'},
    {['key']='craft', ['value']='upholsterer'},
    {['key']='craft', ['value']='watchmaker'},
    {['key']='craft', ['value']='water_well_drilling'},
    {['key']='craft', ['value']='window_construction'},
    {['key']='craft', ['value']='winery'},
    -- Emergency
    {['key']='emergency', ['value']='undefined'},
    {['key']='emergency', ['value']='ambulance_station'},
    {['key']='emergency', ['value']='defibrillator'},
    {['key']='emergency', ['value']='landing_site'},
    {['key']='emergency', ['value']='emergency_ward_entrance'},
    {['key']='emergency', ['value']='dry_riser_inlet'},
    {['key']='emergency', ['value']='fire_alarm_box'},
    {['key']='emergency', ['value']='fire_extinguisher'},
    {['key']='emergency', ['value']='fire_hose'},
    {['key']='emergency', ['value']='fire_hydrant'},
    {['key']='emergency', ['value']='water_tank'},
    {['key']='emergency', ['value']='suction_point'},
    {['key']='emergency', ['value']='lifeguard'},
    {['key']='emergency', ['value']='life_ring'},
    {['key']='emergency', ['value']='lifeguard_base'},
    {['key']='emergency', ['value']='lifeguard_place'},
    {['key']='emergency', ['value']='lifeguard_tower'},
    {['key']='emergency', ['value']='lifeguard_platform'},
    {['key']='emergency', ['value']='assembly_point'},
    {['key']='emergency', ['value']='phone'},
    {['key']='emergency', ['value']='siren'},
    {['key']='emergency', ['value']='ses_station'},
    {['key']='emergency', ['value']='drinking_water'},
    -- Geological
    {['key']='geological', ['value']='undefined'},
    {['key']='geological', ['value']='moraine'},
    {['key']='geological', ['value']='outcrop'},
    {['key']='geological', ['value']='palaeontological_site'},
    {['key']='geological', ['value']='volcanic_caldera_rim	'},
    {['key']='geological', ['value']='volcanic_vent'},
    {['key']='geological', ['value']='volcanic_lava_field'},
    {['key']='geological', ['value']='columnar_jointing'},
    -- Healthcare
    {['key']='healthcare', ['value']='undefined'},
    {['key']='healthcare', ['value']='alternative'},
    {['key']='healthcare', ['value']='audiologist'},
    {['key']='healthcare', ['value']='birthing_center'},
    {['key']='healthcare', ['value']='blood_bank'},
    {['key']='healthcare', ['value']='blood_donation'},
    {['key']='healthcare', ['value']='counselling'},
    {['key']='healthcare', ['value']='dialysis'},
    {['key']='healthcare', ['value']='hospice'},
    {['key']='healthcare', ['value']='laboratory'},
    {['key']='healthcare', ['value']='midwife'},
    {['key']='healthcare', ['value']='nurse'},
    {['key']='healthcare', ['value']='occupational_therapist'},
    {['key']='healthcare', ['value']='optometrist'},
    {['key']='healthcare', ['value']='physiotherapist'},
    {['key']='healthcare', ['value']='podiatrist'},
    {['key']='healthcare', ['value']='psychotherapist'},
    {['key']='healthcare', ['value']='rehabilitation'},
    {['key']='healthcare', ['value']='sample_collection'},
    {['key']='healthcare', ['value']='speech_therapist'},
    {['key']='healthcare', ['value']='vaccination_centre'},
    -- Highway
    {['key']='highway', ['value']='undefined'},
    {['key']='highway', ['value']='motorway'},
    {['key']='highway', ['value']='trunk'},
    {['key']='highway', ['value']='primary'},
    {['key']='highway', ['value']='secondary'},
    {['key']='highway', ['value']='tertiary'},
    {['key']='highway', ['value']='unclassified'},
    {['key']='highway', ['value']='residential'},
    {['key']='highway', ['value']='motorway_link'},
    {['key']='highway', ['value']='trunk_link'},
    {['key']='highway', ['value']='primary_link'},
    {['key']='highway', ['value']='secondary_link'},
    {['key']='highway', ['value']='tertiary_link'},
    {['key']='highway', ['value']='living_street'},
    {['key']='highway', ['value']='service'},
    {['key']='highway', ['value']='pedestrian'},
    {['key']='highway', ['value']='track'},
    {['key']='highway', ['value']='bus_guideway'},
    {['key']='highway', ['value']='escape'},
    {['key']='highway', ['value']='raceway'},
    {['key']='highway', ['value']='road'},
    {['key']='highway', ['value']='footway'},
    {['key']='highway', ['value']='bridleway'},
    {['key']='highway', ['value']='steps'},
    {['key']='highway', ['value']='corridor'},
    {['key']='highway', ['value']='path'},
    {['key']='highway', ['value']='sidewalk'},
    {['key']='highway', ['value']='crossing'},
    {['key']='highway', ['value']='cycleway'},
    {['key']='highway', ['value']='proposed'},
    {['key']='highway', ['value']='construction'},
    {['key']='highway', ['value']='bus_stop'},
    {['key']='highway', ['value']='elevator'},
    {['key']='highway', ['value']='emergency_bay'},
    {['key']='highway', ['value']='emergency_access_point'},
    {['key']='highway', ['value']='give_way'},
    {['key']='highway', ['value']='phone'},
    {['key']='highway', ['value']='milestone'},
    {['key']='highway', ['value']='mini_roundabout'},
    {['key']='highway', ['value']='motorway_junction'},
    {['key']='highway', ['value']='passing_place'},
    {['key']='highway', ['value']='platform'},
    {['key']='highway', ['value']='rest_area'},
    {['key']='highway', ['value']='speed_camera'},
    {['key']='highway', ['value']='street_lamp'},
    {['key']='highway', ['value']='services'},
    {['key']='highway', ['value']='stop'},
    {['key']='highway', ['value']='traffic_mirror'},
    {['key']='highway', ['value']='traffic_signals'},
    {['key']='highway', ['value']='trailhead'},
    {['key']='highway', ['value']='turning_circle'},
    {['key']='highway', ['value']='turning_loop'},
    {['key']='highway', ['value']='toll_gantry'},
    -- Historic
    {['key']='historic', ['value']='undefined'},
    {['key']='historic', ['value']='aircraft'},
    {['key']='historic', ['value']='aqueduct'},
    {['key']='historic', ['value']='archaeological_site'},
    {['key']='historic', ['value']='battlefield'},
    {['key']='historic', ['value']='bomb_crater'},
    {['key']='historic', ['value']='boundary_stone'},
    {['key']='historic', ['value']='building'},
    {['key']='historic', ['value']='cannon'},
    {['key']='historic', ['value']='castle'},
    {['key']='historic', ['value']='castle_wall'},
    {['key']='historic', ['value']='charcoal_pile'},
    {['key']='historic', ['value']='church'},
    {['key']='historic', ['value']='city_gate'},
    {['key']='historic', ['value']='citywalls'},
    {['key']='historic', ['value']='creamery'},
    {['key']='historic', ['value']='farm'},
    {['key']='historic', ['value']='fort'},
    {['key']='historic', ['value']='gallows'},
    {['key']='historic', ['value']='highwater_mark'},
    {['key']='historic', ['value']='locomotive'},
    {['key']='historic', ['value']='manor'},
    {['key']='historic', ['value']='memorial'},
    {['key']='historic', ['value']='milestone'},
    {['key']='historic', ['value']='monastery'},
    {['key']='historic', ['value']='monument'},
    {['key']='historic', ['value']='optical_telegraph'},
    {['key']='historic', ['value']='pa'},
    {['key']='historic', ['value']='pillory'},
    {['key']='historic', ['value']='railway_car'},
    {['key']='historic', ['value']='ruins'},
    {['key']='historic', ['value']='rune_stone'},
    {['key']='historic', ['value']='ship'},
    {['key']='historic', ['value']='tank'},
    {['key']='historic', ['value']='tomb'},
    {['key']='historic', ['value']='tower'},
    {['key']='historic', ['value']='vehicle'},
    {['key']='historic', ['value']='wayside_cross'},
    {['key']='historic', ['value']='wayside_shrine'},
    {['key']='historic', ['value']='wreck'},
    {['key']='historic', ['value']='yes'},
    -- Landuse
    {['key']='landuse', ['value']='undefined'},
    {['key']='landuse', ['value']='commercial'},
    {['key']='landuse', ['value']='construction'},
    {['key']='landuse', ['value']='education'},
    {['key']='landuse', ['value']='industrial'},
    {['key']='landuse', ['value']='residential'},
    {['key']='landuse', ['value']='retail'},
    {['key']='landuse', ['value']='allotments'},
    {['key']='landuse', ['value']='farmland'},
    {['key']='landuse', ['value']='farmyard'},
    {['key']='landuse', ['value']='flowerbed'},
    {['key']='landuse', ['value']='forest'},
    {['key']='landuse', ['value']='meadow'},
    {['key']='landuse', ['value']='orchard'},
    {['key']='landuse', ['value']='vineyard'},
    {['key']='landuse', ['value']='aquaculture'},
    {['key']='landuse', ['value']='basin'},
    {['key']='landuse', ['value']='salt_pond'},
    {['key']='landuse', ['value']='brownfield'},
    {['key']='landuse', ['value']='cemetery'},
    {['key']='landuse', ['value']='depot'},
    {['key']='landuse', ['value']='garages'},
    {['key']='landuse', ['value']='grass'},
    {['key']='landuse', ['value']='greenfield'},
    {['key']='landuse', ['value']='greenhouse_horticulture'},
    {['key']='landuse', ['value']='landfill'},
    {['key']='landuse', ['value']='military'},
    {['key']='landuse', ['value']='pasture'},
    {['key']='landuse', ['value']='peat_cutting'},
    {['key']='landuse', ['value']='plant_nursery'},
    {['key']='landuse', ['value']='port'},
    {['key']='landuse', ['value']='quarry'},
    {['key']='landuse', ['value']='railway'},
    {['key']='landuse', ['value']='recreation_ground'},
    {['key']='landuse', ['value']='religious'},
    {['key']='landuse', ['value']='reservoir'},
    {['key']='landuse', ['value']='village_green'},
    {['key']='landuse', ['value']='winter_sports'},
    -- Leisure
    {['key']='leisure', ['value']='undefined'},
    {['key']='leisure', ['value']='adult_gaming_centre'},
    {['key']='leisure', ['value']='amusement_arcade'},
    {['key']='leisure', ['value']='beach_resort'},
    {['key']='leisure', ['value']='bandstand'},
    {['key']='leisure', ['value']='bird_hide'},
    {['key']='leisure', ['value']='common'},
    {['key']='leisure', ['value']='dance'},
    {['key']='leisure', ['value']='disc_golf_course'},
    {['key']='leisure', ['value']='dog_park'},
    {['key']='leisure', ['value']='escape_game'},
    {['key']='leisure', ['value']='firepit'},
    {['key']='leisure', ['value']='fishing'},
    {['key']='leisure', ['value']='fitness_centre'},
    {['key']='leisure', ['value']='fitness_station'},
    {['key']='leisure', ['value']='garden'},
    {['key']='leisure', ['value']='golf_course'},
    {['key']='leisure', ['value']='hackerspace'},
    {['key']='leisure', ['value']='horse_riding'},
    {['key']='leisure', ['value']='ice_rink'},
    {['key']='leisure', ['value']='marina'},
    {['key']='leisure', ['value']='miniature_golf'},
    {['key']='leisure', ['value']='nature_reserve'},
    {['key']='leisure', ['value']='park'},
    {['key']='leisure', ['value']='picnic_table'},
    {['key']='leisure', ['value']='pitch'},
    {['key']='leisure', ['value']='playground'},
    {['key']='leisure', ['value']='slipway'},
    {['key']='leisure', ['value']='sports_centre'},
    {['key']='leisure', ['value']='stadium'},
    {['key']='leisure', ['value']='summer_camp'},
    {['key']='leisure', ['value']='swimming_area'},
    {['key']='leisure', ['value']='swimming_pool'},
    {['key']='leisure', ['value']='track'},
    {['key']='leisure', ['value']='water_park'},
    {['key']='leisure', ['value']='wildlife_hide'},
    -- Man_made
    {['key']='man_made', ['value']='undefined'},
    {['key']='man_made', ['value']='adit'},
    {['key']='man_made', ['value']='beacon'},
    {['key']='man_made', ['value']='breakwater'},
    {['key']='man_made', ['value']='bridge'},
    {['key']='man_made', ['value']='bunker_silo'},
    {['key']='man_made', ['value']='campanile'},
    {['key']='man_made', ['value']='carpet_hanger'},
    {['key']='man_made', ['value']='chimney'},
    {['key']='man_made', ['value']='column'},
    {['key']='man_made', ['value']='communications_tower'},
    {['key']='man_made', ['value']='crane'},
    {['key']='man_made', ['value']='cross'},
    {['key']='man_made', ['value']='cutline'},
    {['key']='man_made', ['value']='clearcut'},
    {['key']='man_made', ['value']='dovecote'},
    {['key']='man_made', ['value']='dyke'},
    {['key']='man_made', ['value']='embankment'},
    {['key']='man_made', ['value']='flagpole'},
    {['key']='man_made', ['value']='gasometer'},
    {['key']='man_made', ['value']='goods_conveyor'},
    {['key']='man_made', ['value']='groyne'},
    {['key']='man_made', ['value']='hot_water_tank'},
    {['key']='man_made', ['value']='kiln'},
    {['key']='man_made', ['value']='lighthouse'},
    {['key']='man_made', ['value']='mast'},
    {['key']='man_made', ['value']='mineshaft'},
    {['key']='man_made', ['value']='monitoring_station'},
    {['key']='man_made', ['value']='obelisk'},
    {['key']='man_made', ['value']='observatory'},
    {['key']='man_made', ['value']='offshore_platform'},
    {['key']='man_made', ['value']='petroleum_well'},
    {['key']='man_made', ['value']='pier'},
    {['key']='man_made', ['value']='pipeline'},
    {['key']='man_made', ['value']='pump'},
    {['key']='man_made', ['value']='pumping_station'},
    {['key']='man_made', ['value']='reservoir_covered'},
    {['key']='man_made', ['value']='silo'},
    {['key']='man_made', ['value']='snow_fence'},
    {['key']='man_made', ['value']='snow_net'},
    {['key']='man_made', ['value']='storage_tank'},
    {['key']='man_made', ['value']='street_cabinet'},
    {['key']='man_made', ['value']='stupa'},
    {['key']='man_made', ['value']='surveillance'},
    {['key']='man_made', ['value']='survey_point'},
    {['key']='man_made', ['value']='tailings_pond'},
    {['key']='man_made', ['value']='telescope'},
    {['key']='man_made', ['value']='tower'},
    {['key']='man_made', ['value']='wastewater_plant'},
    {['key']='man_made', ['value']='watermill'},
    {['key']='man_made', ['value']='water_tower'},
    {['key']='man_made', ['value']='water_well'},
    {['key']='man_made', ['value']='water_tap'},
    {['key']='man_made', ['value']='water_works'},
    {['key']='man_made', ['value']='wildlife_crossing'},
    {['key']='man_made', ['value']='windmill'},
    {['key']='man_made', ['value']='works'},
    {['key']='man_made', ['value']='yes'},
    -- Military
    {['key']='military', ['value']='undefined'},
    {['key']='military', ['value']='airfield'},
    {['key']='military', ['value']='ammunition'},
    {['key']='military', ['value']='base'},
    {['key']='military', ['value']='bunker'},
    {['key']='military', ['value']='barracks'},
    {['key']='military', ['value']='checkpoint'},
    {['key']='military', ['value']='danger_area'},
    {['key']='military', ['value']='naval_base'},
    {['key']='military', ['value']='nuclear_explosion_site'},
    {['key']='military', ['value']='obstacle_course'},
    {['key']='military', ['value']='office'},
    {['key']='military', ['value']='range'},
    {['key']='military', ['value']='training_area'},
    {['key']='military', ['value']='trench'},
    -- Natural
    {['key']='natural', ['value']='undefined'},
    {['key']='natural', ['value']='fell'},
    {['key']='natural', ['value']='grassland'},
    {['key']='natural', ['value']='heath'},
    {['key']='natural', ['value']='moor'},
    {['key']='natural', ['value']='scrub'},
    {['key']='natural', ['value']='shrubbery'},
    {['key']='natural', ['value']='tree'},
    {['key']='natural', ['value']='tree_row'},
    {['key']='natural', ['value']='tundra'},
    {['key']='natural', ['value']='wood'},
    {['key']='natural', ['value']='bay'},
    {['key']='natural', ['value']='beach'},
    {['key']='natural', ['value']='blowhole'},
    {['key']='natural', ['value']='cape'},
    {['key']='natural', ['value']='coastline'},
    {['key']='natural', ['value']='crevasse'},
    {['key']='natural', ['value']='geyser'},
    {['key']='natural', ['value']='glacier'},
    {['key']='natural', ['value']='hot_spring'},
    {['key']='natural', ['value']='isthmus'},
    {['key']='natural', ['value']='mud'},
    {['key']='natural', ['value']='peninsula'},
    {['key']='natural', ['value']='reef'},
    {['key']='natural', ['value']='shingle'},
    {['key']='natural', ['value']='shoal'},
    {['key']='natural', ['value']='spring'},
    {['key']='natural', ['value']='strait'},
    {['key']='natural', ['value']='water'},
    {['key']='natural', ['value']='wetland'},
    {['key']='natural', ['value']='arch'},
    {['key']='natural', ['value']='arete'},
    {['key']='natural', ['value']='bare_rock'},
    {['key']='natural', ['value']='cave_entrance'},
    {['key']='natural', ['value']='cliff'},
    {['key']='natural', ['value']='dune'},
    {['key']='natural', ['value']='earth_bank'},
    {['key']='natural', ['value']='fumarole'},
    {['key']='natural', ['value']='hill'},
    {['key']='natural', ['value']='peak'},
    {['key']='natural', ['value']='ridge'},
    {['key']='natural', ['value']='rock'},
    {['key']='natural', ['value']='saddle'},
    {['key']='natural', ['value']='sand'},
    {['key']='natural', ['value']='scree'},
    {['key']='natural', ['value']='sinkhole'},
    {['key']='natural', ['value']='stone'},
    {['key']='natural', ['value']='valley'},
    {['key']='natural', ['value']='volcano'},
    -- Office
    {['key']='office', ['value']='undefined'},
    {['key']='office', ['value']='accountant'},
    {['key']='office', ['value']='adoption_agency'},
    {['key']='office', ['value']='advertising_agency'},
    {['key']='office', ['value']='architect'},
    {['key']='office', ['value']='association'},
    {['key']='office', ['value']='bail_bond_agent'},
    {['key']='office', ['value']='charity'},
    {['key']='office', ['value']='company'},
    {['key']='office', ['value']='consulting'},
    {['key']='office', ['value']='courier'},
    {['key']='office', ['value']='coworking'},
    {['key']='office', ['value']='diplomatic'},
    {['key']='office', ['value']='educational_institution'},
    {['key']='office', ['value']='employment_agency'},
    {['key']='office', ['value']='energy_supplier'},
    {['key']='office', ['value']='engineer'},
    {['key']='office', ['value']='estate_agent'},
    {['key']='office', ['value']='financial'},
    {['key']='office', ['value']='financial_advisor'},
    {['key']='office', ['value']='forestry'},
    {['key']='office', ['value']='foundation'},
    {['key']='office', ['value']='geodesist'},
    {['key']='office', ['value']='government'},
    {['key']='office', ['value']='graphic_design'},
    {['key']='office', ['value']='guide'},
    {['key']='office', ['value']='harbour_master'},
    {['key']='office', ['value']='insurance'},
    {['key']='office', ['value']='it'},
    {['key']='office', ['value']='lawyer'},
    {['key']='office', ['value']='logistics'},
    {['key']='office', ['value']='moving_company'},
    {['key']='office', ['value']='newspaper'},
    {['key']='office', ['value']='ngo'},
    {['key']='office', ['value']='notary'},
    {['key']='office', ['value']='political_party'},
    {['key']='office', ['value']='private_investigator'},
    {['key']='office', ['value']='property_management'},
    {['key']='office', ['value']='quango'},
    {['key']='office', ['value']='real_estate_agent'},
    {['key']='office', ['value']='religion'},
    {['key']='office', ['value']='research'},
    {['key']='office', ['value']='security'},
    {['key']='office', ['value']='surveyor'},
    {['key']='office', ['value']='tax'},
    {['key']='office', ['value']='tax_advisor'},
    {['key']='office', ['value']='telecommunication'},
    {['key']='office', ['value']='travel_agent'},
    {['key']='office', ['value']='union'},
    {['key']='office', ['value']='visa'},
    {['key']='office', ['value']='water_utility'},
    {['key']='office', ['value']='yes'},
    -- Place
    {['key']='place', ['value']='undefined'},
    {['key']='place', ['value']='country'},
    {['key']='place', ['value']='state'},
    {['key']='place', ['value']='region'},
    {['key']='place', ['value']='province'},
    {['key']='place', ['value']='district'},
    {['key']='place', ['value']='county'},
    {['key']='place', ['value']='municipality'},
    {['key']='place', ['value']='city'},
    {['key']='place', ['value']='borough'},
    {['key']='place', ['value']='suburb'},
    {['key']='place', ['value']='quarter'},
    {['key']='place', ['value']='neighbourhood'},
    {['key']='place', ['value']='city_block'},
    {['key']='place', ['value']='plot'},
    {['key']='place', ['value']='town'},
    {['key']='place', ['value']='village'},
    {['key']='place', ['value']='hamlet'},
    {['key']='place', ['value']='isolated_dwelling'},
    {['key']='place', ['value']='farm'},
    {['key']='place', ['value']='allotments'},
    {['key']='place', ['value']='continent'},
    {['key']='place', ['value']='archipelago'},
    {['key']='place', ['value']='island'},
    {['key']='place', ['value']='islet'},
    {['key']='place', ['value']='square'},
    {['key']='place', ['value']='locality'},
    {['key']='place', ['value']='sea'},
    {['key']='place', ['value']='ocean'},
    -- Power
    {['key']='power', ['value']='undefined'},
    {['key']='power', ['value']='cable'},
    {['key']='power', ['value']='catenary_mast'},
    {['key']='power', ['value']='compensator'},
    {['key']='power', ['value']='connection'},
    {['key']='power', ['value']='converter'},
    {['key']='power', ['value']='generator'},
    {['key']='power', ['value']='heliostat'},
    {['key']='power', ['value']='insulator'},
    {['key']='power', ['value']='line'},
    {['key']='power', ['value']='busbar'},
    {['key']='power', ['value']='bay'},
    {['key']='power', ['value']='minor_line'},
    {['key']='power', ['value']='plant'},
    {['key']='power', ['value']='pole'},
    {['key']='power', ['value']='portal'},
    {['key']='power', ['value']='substation'},
    {['key']='power', ['value']='switch'},
    {['key']='power', ['value']='switchgear'},
    {['key']='power', ['value']='terminal'},
    {['key']='power', ['value']='tower'},
    {['key']='power', ['value']='transformer'},
    -- Public Transport
    {['key']='public_transport', ['value']='undefined'},
    {['key']='public_transport', ['value']='stop_position'},
    {['key']='public_transport', ['value']='platform'},
    {['key']='public_transport', ['value']='station'},
    {['key']='public_transport', ['value']='stop_area'},
    -- Railway
    {['key']='railway', ['value']='undefined'},
    {['key']='railway', ['value']='abandoned'},
    {['key']='railway', ['value']='construction'},
    {['key']='railway', ['value']='disused'},
    {['key']='railway', ['value']='funicular'},
    {['key']='railway', ['value']='light_rail'},
    {['key']='railway', ['value']='miniature'},
    {['key']='railway', ['value']='monorail'},
    {['key']='railway', ['value']='narrow_gauge'},
    {['key']='railway', ['value']='preserved'},
    {['key']='railway', ['value']='rail'},
    {['key']='railway', ['value']='subway'},
    {['key']='railway', ['value']='tram'},
    {['key']='railway', ['value']='halt'},
    {['key']='railway', ['value']='platform'},
    {['key']='railway', ['value']='station'},
    {['key']='railway', ['value']='subway_entrance'},
    {['key']='railway', ['value']='tram_stop'},
    {['key']='railway', ['value']='buffer_stop'},
    {['key']='railway', ['value']='derail'},
    {['key']='railway', ['value']='crossing'},
    {['key']='railway', ['value']='level_crossing'},
    {['key']='railway', ['value']='signal'},
    {['key']='railway', ['value']='switch'},
    {['key']='railway', ['value']='railway_crossing'},
    {['key']='railway', ['value']='turntable'},
    {['key']='railway', ['value']='roundhouse'},
    {['key']='railway', ['value']='traverser'},
    {['key']='railway', ['value']='wash'},
    {['key']='railway', ['value']='water_crane'},
    -- Route
    {['key']='route', ['value']='undefined'},
    {['key']='route', ['value']='bicycle'},
    {['key']='route', ['value']='bus'},
    {['key']='route', ['value']='canoe'},
    {['key']='route', ['value']='detour'},
    {['key']='route', ['value']='ferry'},
    {['key']='route', ['value']='fitness_trail'},
    {['key']='route', ['value']='foot'},
    {['key']='route', ['value']='hiking'},
    {['key']='route', ['value']='horse'},
    {['key']='route', ['value']='inline_skates'},
    {['key']='route', ['value']='light_rail'},
    {['key']='route', ['value']='mtb'},
    {['key']='route', ['value']='nordic_walking'},
    {['key']='route', ['value']='pipeline'},
    {['key']='route', ['value']='piste'},
    {['key']='route', ['value']='power'},
    {['key']='route', ['value']='railway'},
    {['key']='route', ['value']='road'},
    {['key']='route', ['value']='running'},
    {['key']='route', ['value']='ski'},
    {['key']='route', ['value']='subway'},
    {['key']='route', ['value']='train'},
    {['key']='route', ['value']='tracks'},
    {['key']='route', ['value']='tram'},
    {['key']='route', ['value']='trolleybus'},
    -- Shop
    {['key']='shop', ['value']='undefined'},
    {['key']='shop', ['value']='alcohol'},
    {['key']='shop', ['value']='bakery'},
    {['key']='shop', ['value']='beverages'},
    {['key']='shop', ['value']='brewing_supplies'},
    {['key']='shop', ['value']='butcher'},
    {['key']='shop', ['value']='cheese'},
    {['key']='shop', ['value']='chocolate'},
    {['key']='shop', ['value']='coffee'},
    {['key']='shop', ['value']='confectionery'},
    {['key']='shop', ['value']='convenience'},
    {['key']='shop', ['value']='deli'},
    {['key']='shop', ['value']='dairy'},
    {['key']='shop', ['value']='farm'},
    {['key']='shop', ['value']='frozen_food'},
    {['key']='shop', ['value']='greengrocer'},
    {['key']='shop', ['value']='health_food'},
    {['key']='shop', ['value']='ice_cream'},
    {['key']='shop', ['value']='organic'},
    {['key']='shop', ['value']='pasta'},
    {['key']='shop', ['value']='pastry'},
    {['key']='shop', ['value']='seafood'},
    {['key']='shop', ['value']='spices'},
    {['key']='shop', ['value']='tea'},
    {['key']='shop', ['value']='wine'},
    {['key']='shop', ['value']='water'},
    {['key']='shop', ['value']='department_store'},
    {['key']='shop', ['value']='general'},
    {['key']='shop', ['value']='kiosk'},
    {['key']='shop', ['value']='mall'},
    {['key']='shop', ['value']='supermarket'},
    {['key']='shop', ['value']='wholesale'},
    {['key']='shop', ['value']='baby_goods'},
    {['key']='shop', ['value']='bag'},
    {['key']='shop', ['value']='boutique'},
    {['key']='shop', ['value']='clothes'},
    {['key']='shop', ['value']='fabric'},
    {['key']='shop', ['value']='fashion'},
    {['key']='shop', ['value']='fashion_accessories'},
    {['key']='shop', ['value']='jewelry'},
    {['key']='shop', ['value']='leather'},
    {['key']='shop', ['value']='sewing'},
    {['key']='shop', ['value']='shoes'},
    {['key']='shop', ['value']='tailor'},
    {['key']='shop', ['value']='watches'},
    {['key']='shop', ['value']='wool'},
    {['key']='shop', ['value']='charity'},
    {['key']='shop', ['value']='second_hand'},
    {['key']='shop', ['value']='variety_store'},
    {['key']='shop', ['value']='beauty'},
    {['key']='shop', ['value']='chemist'},
    {['key']='shop', ['value']='cosmetics'},
    {['key']='shop', ['value']='drugstore'},
    {['key']='shop', ['value']='erotic'},
    {['key']='shop', ['value']='hairdresser'},
    {['key']='shop', ['value']='hairdresser_supply'},
    {['key']='shop', ['value']='hearing_aids'},
    {['key']='shop', ['value']='herbalist'},
    {['key']='shop', ['value']='massage'},
    {['key']='shop', ['value']='medical_supply'},
    {['key']='shop', ['value']='nutrition_supplements'},
    {['key']='shop', ['value']='optician'},
    {['key']='shop', ['value']='perfumery'},
    {['key']='shop', ['value']='tattoo'},
    {['key']='shop', ['value']='agrarian'},
    {['key']='shop', ['value']='appliance'},
    {['key']='shop', ['value']='bathroom_furnishing'},
    {['key']='shop', ['value']='doityourself'},
    {['key']='shop', ['value']='electrical'},
    {['key']='shop', ['value']='energy'},
    {['key']='shop', ['value']='fireplace'},
    {['key']='shop', ['value']='florist'},
    {['key']='shop', ['value']='garden_centre'},
    {['key']='shop', ['value']='garden_furniture'},
    {['key']='shop', ['value']='gas'},
    {['key']='shop', ['value']='glaziery'},
    {['key']='shop', ['value']='groundskeeping'},
    {['key']='shop', ['value']='hardware'},
    {['key']='shop', ['value']='houseware'},
    {['key']='shop', ['value']='locksmith'},
    {['key']='shop', ['value']='paint'},
    {['key']='shop', ['value']='security'},
    {['key']='shop', ['value']='trade'},
    {['key']='shop', ['value']='windows'},
    {['key']='shop', ['value']='antiques'},
    {['key']='shop', ['value']='bed'},
    {['key']='shop', ['value']='candles'},
    {['key']='shop', ['value']='carpet'},
    {['key']='shop', ['value']='curtain'},
    {['key']='shop', ['value']='doors'},
    {['key']='shop', ['value']='flooring'},
    {['key']='shop', ['value']='furniture'},
    {['key']='shop', ['value']='household_linen'},
    {['key']='shop', ['value']='interior_decoration'},
    {['key']='shop', ['value']='kitchen'},
    {['key']='shop', ['value']='lamps'},
    {['key']='shop', ['value']='lighting'},
    {['key']='shop', ['value']='tiles'},
    {['key']='shop', ['value']='window_blind'},
    {['key']='shop', ['value']='computer'},
    {['key']='shop', ['value']='electronics'},
    {['key']='shop', ['value']='hifi'},
    {['key']='shop', ['value']='mobile_phone'},
    {['key']='shop', ['value']='radiotechnics'},
    {['key']='shop', ['value']='vacuum_cleaner'},
    {['key']='shop', ['value']='atv'},
    {['key']='shop', ['value']='bicycle'},
    {['key']='shop', ['value']='boat'},
    {['key']='shop', ['value']='car'},
    {['key']='shop', ['value']='car_repair'},
    {['key']='shop', ['value']='car_parts'},
    {['key']='shop', ['value']='caravan'},
    {['key']='shop', ['value']='fuel'},
    {['key']='shop', ['value']='fishing'},
    {['key']='shop', ['value']='free_flying'},
    {['key']='shop', ['value']='golf'},
    {['key']='shop', ['value']='hunting'},
    {['key']='shop', ['value']='jetski'},
    {['key']='shop', ['value']='military_surplus'},
    {['key']='shop', ['value']='motorcycle'},
    {['key']='shop', ['value']='outdoor'},
    {['key']='shop', ['value']='scuba_diving'},
    {['key']='shop', ['value']='ski'},
    {['key']='shop', ['value']='snowmobile'},
    {['key']='shop', ['value']='sports'},
    {['key']='shop', ['value']='swimming_pool'},
    {['key']='shop', ['value']='trailer'},
    {['key']='shop', ['value']='tyres'},
    {['key']='shop', ['value']='art'}, 
    {['key']='shop', ['value']='camera'}, 
    {['key']='shop', ['value']='collector'},
    {['key']='shop', ['value']='craft'},
    {['key']='shop', ['value']='frame'},
    {['key']='shop', ['value']='games'},
    {['key']='shop', ['value']='model'},
    {['key']='shop', ['value']='music'},
    {['key']='shop', ['value']='musical_instrument'},
    {['key']='shop', ['value']='photo'},
    {['key']='shop', ['value']='trophy'},
    {['key']='shop', ['value']='video'},
    {['key']='shop', ['value']='video_games'},
    {['key']='shop', ['value']='anime'},
    {['key']='shop', ['value']='books'},
    {['key']='shop', ['value']='gift'},
    {['key']='shop', ['value']='lottery'},
    {['key']='shop', ['value']='newsagent'},
    {['key']='shop', ['value']='stationery'},
    {['key']='shop', ['value']='ticket'},
    {['key']='shop', ['value']='bookmaker'},
    {['key']='shop', ['value']='cannabis'},
    {['key']='shop', ['value']='copyshop'},
    {['key']='shop', ['value']='dry_cleaning'},
    {['key']='shop', ['value']='e-cigarette'},
    {['key']='shop', ['value']='funeral_directors'},
    {['key']='shop', ['value']='laundry'},
    {['key']='shop', ['value']='money_lender'},
    {['key']='shop', ['value']='outpost'},
    {['key']='shop', ['value']='party'},
    {['key']='shop', ['value']='pawnbroker'},
    {['key']='shop', ['value']='pet'},
    {['key']='shop', ['value']='pet_grooming'},
    {['key']='shop', ['value']='pest_control'},
    {['key']='shop', ['value']='pyrotechnics'},
    {['key']='shop', ['value']='religion'},
    {['key']='shop', ['value']='storage_rental'},
    {['key']='shop', ['value']='tobacco'},
    {['key']='shop', ['value']='toys'},
    {['key']='shop', ['value']='travel_agency'},
    {['key']='shop', ['value']='vacant'},
    {['key']='shop', ['value']='weapons'},
    {['key']='shop', ['value']='yes'},
    -- Sport
    {['key']='sport', ['value']='undefined'},
    {['key']='sport', ['value']='9pin'},
    {['key']='sport', ['value']='10pin'},
    {['key']='sport', ['value']='american_football'},
    {['key']='sport', ['value']='aikido'},
    {['key']='sport', ['value']='archery'},
    {['key']='sport', ['value']='athletics'},
    {['key']='sport', ['value']='australian_football'},
    {['key']='sport', ['value']='badminton'},
    {['key']='sport', ['value']='bandy'},
    {['key']='sport', ['value']='baseball'},
    {['key']='sport', ['value']='basketball'},
    {['key']='sport', ['value']='beachvolleyball'},
    {['key']='sport', ['value']='biathlon'},
    {['key']='sport', ['value']='billiards'},
    {['key']='sport', ['value']='bmx'},
    {['key']='sport', ['value']='bobsleigh'},
    {['key']='sport', ['value']='boules'},
    {['key']='sport', ['value']='bowls'},
    {['key']='sport', ['value']='boxing'},
    {['key']='sport', ['value']='bullfighting'},
    {['key']='sport', ['value']='canadian_football'},
    {['key']='sport', ['value']='canoe'},
    {['key']='sport', ['value']='chess'},
    {['key']='sport', ['value']='cliff_diving'},
    {['key']='sport', ['value']='climbing'},
    {['key']='sport', ['value']='climbing_adventure'},
    {['key']='sport', ['value']='cockfighting'},
    {['key']='sport', ['value']='cricket'},
    {['key']='sport', ['value']='crossfit'},
    {['key']='sport', ['value']='croquet'},
    {['key']='sport', ['value']='curling'},
    {['key']='sport', ['value']='cycle_polo'},
    {['key']='sport', ['value']='cycling'},
    {['key']='sport', ['value']='darts'},
    {['key']='sport', ['value']='dog_agility'},
    {['key']='sport', ['value']='dog_racing'},
    {['key']='sport', ['value']='equestrian'},
    {['key']='sport', ['value']='fencing'},
    {['key']='sport', ['value']='field_hockey'},
    {['key']='sport', ['value']='fitness'},
    {['key']='sport', ['value']='five-a-side'},
    {['key']='sport', ['value']='floorball'},
    {['key']='sport', ['value']='four_square'},
    {['key']='sport', ['value']='free_flying'},
    {['key']='sport', ['value']='futsal'},
    {['key']='sport', ['value']='gaelic_games'},
    {['key']='sport', ['value']='gaga'},
    {['key']='sport', ['value']='golf'},
    {['key']='sport', ['value']='gymnastics'},
    {['key']='sport', ['value']='handball'},
    {['key']='sport', ['value']='hapkido'},
    {['key']='sport', ['value']='horseshoes'},
    {['key']='sport', ['value']='horse_racing'},
    {['key']='sport', ['value']='ice_hockey'},
    {['key']='sport', ['value']='ice_skating'},
    {['key']='sport', ['value']='ice_stock'},
    {['key']='sport', ['value']='jiu-jitsu'},
    {['key']='sport', ['value']='judo'},
    {['key']='sport', ['value']='karate'},
    {['key']='sport', ['value']='karting'},
    {['key']='sport', ['value']='kickboxing'},
    {['key']='sport', ['value']='kitesurfing'},
    {['key']='sport', ['value']='korfball'},
    {['key']='sport', ['value']='krachtbal'},
    {['key']='sport', ['value']='lacrosse'},
    {['key']='sport', ['value']='martial_arts'},
    {['key']='sport', ['value']='miniature_golf'},
    {['key']='sport', ['value']='model_aerodrome'},
    {['key']='sport', ['value']='motocross'},
    {['key']='sport', ['value']='motor'},
    {['key']='sport', ['value']='multi'},
    {['key']='sport', ['value']='netball'},
    {['key']='sport', ['value']='obstacle_course'},
    {['key']='sport', ['value']='orienteering'},
    {['key']='sport', ['value']='paddle_tennis'},
    {['key']='sport', ['value']='padel'},
    {['key']='sport', ['value']='parachuting'},
    {['key']='sport', ['value']='parkour'},
    {['key']='sport', ['value']='paragliding'},
    {['key']='sport', ['value']='pelota'},
    {['key']='sport', ['value']='pesäpallo'},
    {['key']='sport', ['value']='pickleball'},
    {['key']='sport', ['value']='pilates'},
    {['key']='sport', ['value']='pole_dance'},
    {['key']='sport', ['value']='racquet'},
    {['key']='sport', ['value']='rc_car'},
    {['key']='sport', ['value']='roller_skating'},
    {['key']='sport', ['value']='rowing'},
    {['key']='sport', ['value']='rugby_league'},
    {['key']='sport', ['value']='rugby_union'},
    {['key']='sport', ['value']='running'},
    {['key']='sport', ['value']='sailing'},
    {['key']='sport', ['value']='scuba_diving'},
    {['key']='sport', ['value']='shooting'},
    {['key']='sport', ['value']='shot-put'},
    {['key']='sport', ['value']='skateboard'},
    {['key']='sport', ['value']='ski_jumping'},
    {['key']='sport', ['value']='skiing'},
    {['key']='sport', ['value']='snooker'},
    {['key']='sport', ['value']='soccer'},
    {['key']='sport', ['value']='speedway'},
    {['key']='sport', ['value']='squash'},
    {['key']='sport', ['value']='sumo'},
    {['key']='sport', ['value']='surfing'},
    {['key']='sport', ['value']='swimming'},
    {['key']='sport', ['value']='table_tennis'},
    {['key']='sport', ['value']='table_soccer'},
    {['key']='sport', ['value']='taekwondo'},
    {['key']='sport', ['value']='tennis'},
    {['key']='sport', ['value']='toboggan'},
    {['key']='sport', ['value']='ultimate'},
    {['key']='sport', ['value']='volleyball'},
    {['key']='sport', ['value']='wakeboarding'},
    {['key']='sport', ['value']='water_polo'},
    {['key']='sport', ['value']='water_ski'},
    {['key']='sport', ['value']='weightlifting'},
    {['key']='sport', ['value']='wrestling'},
    {['key']='sport', ['value']='yoga'},
    {['key']='sport', ['value']='zurkhaneh_sport'},
    -- Telecom
    {['key']='telecom', ['value']='undefined'},
    {['key']='telecom', ['value']='exchange'},
    {['key']='telecom', ['value']='connection_point'},
    {['key']='telecom', ['value']='distribution_point'},
    {['key']='telecom', ['value']='service_device'},
    {['key']='telecom', ['value']='data_center'},
    -- Tourism
    {['key']='tourism', ['value']='undefined'},
    {['key']='tourism', ['value']='alpine_hut'},
    {['key']='tourism', ['value']='apartment'},
    {['key']='tourism', ['value']='aquarium'},
    {['key']='tourism', ['value']='artwork'},
    {['key']='tourism', ['value']='attraction'},
    {['key']='tourism', ['value']='camp_pitch'},
    {['key']='tourism', ['value']='camp_site'},
    {['key']='tourism', ['value']='caravan_site'},
    {['key']='tourism', ['value']='chalet'},
    {['key']='tourism', ['value']='gallery'},
    {['key']='tourism', ['value']='guest_house'},
    {['key']='tourism', ['value']='hostel'},
    {['key']='tourism', ['value']='hotel'},
    {['key']='tourism', ['value']='information'},
    {['key']='tourism', ['value']='motel'},
    {['key']='tourism', ['value']='museum'},
    {['key']='tourism', ['value']='picnic_site'},
    {['key']='tourism', ['value']='theme_park'},
    {['key']='tourism', ['value']='viewpoint'},
    {['key']='tourism', ['value']='wilderness_hut'},
    {['key']='tourism', ['value']='zoo'},
    {['key']='tourism', ['value']='yes'},
    -- Water
    {['key']='water', ['value']='undefined'},
    {['key']='water', ['value']='river'},
    {['key']='water', ['value']='oxbow'},
    {['key']='water', ['value']='canal'},
    {['key']='water', ['value']='ditch'},
    {['key']='water', ['value']='lock'},
    {['key']='water', ['value']='fish_pass'},
    {['key']='water', ['value']='lake'},
    {['key']='water', ['value']='reservoir'},
    {['key']='water', ['value']='pond'},
    {['key']='water', ['value']='basin'},
    {['key']='water', ['value']='lagoon'},
    {['key']='water', ['value']='stream_pool'},
    {['key']='water', ['value']='reflecting_pool'},
    {['key']='water', ['value']='moat'},
    {['key']='water', ['value']='wastewater'},
    -- Waterway
    {['key']='waterway', ['value']='undefined'},
    {['key']='waterway', ['value']='river'},
    {['key']='waterway', ['value']='riverbank'},
    {['key']='waterway', ['value']='stream'},
    {['key']='waterway', ['value']='tidal_channel'},
    {['key']='waterway', ['value']='canal'},
    {['key']='waterway', ['value']='drain'},
    {['key']='waterway', ['value']='ditch'},
    {['key']='waterway', ['value']='pressurised'},
    {['key']='waterway', ['value']='wadi'},
    {['key']='waterway', ['value']='fairway'},
    {['key']='waterway', ['value']='dock'},
    {['key']='waterway', ['value']='boatyard'},
    {['key']='waterway', ['value']='dam'},
    {['key']='waterway', ['value']='weir'},
    {['key']='waterway', ['value']='waterfall '},
    {['key']='waterway', ['value']='lock_gate'},
    {['key']='waterway', ['value']='soakhole'},
    {['key']='waterway', ['value']='turning_point'},
    {['key']='waterway', ['value']='water_point'},
    {['key']='waterway', ['value']='fuel'}
}


local map_features = {
    'aerialway',
    'aeroway',
    'amenity',
    'barrier',
    'boundary',
    'building',
    'craft',
    'emergency',
    'geological',
    'healthcare',
    'highway',
    'historic',
    'landuse',
    'leisure',
    'man_made',
    'military',
    'natural',
    'office',
    'place',
    'power',
    'public_transport',
    'railway',
    'route',
    'shop',
    'sport',
    'telecom',
    'tourism',
    'water',
    'waterway'
}

-- Helper function to check if lua table contains a value
local function list_contains(list, value)
    for _, v in pairs(list) do
        if v == value then
            return true
        end
    end
    return false
end

local function get_undefined_subclass(class)
    for classcode, feature in pairs(classifications) do
        if feature['key'] == class then
            if feature['value'] == 'undefined' then
                return classcode
            end
        end
    end
end

-- Helper function to get classcode from classifications table
local function get_classcode(key, value)
    for classcode, feature in pairs(classifications) do
        if feature['key'] == key then
            if feature['value'] == value then
                return classcode
            else
                return get_undefined_subclass(key)
            end
            
        end
    end
end

-- Helper function to reformat the timestamp from osm to date in database
local function reformat_date(object_timestamp)
    return os.date('!%Y-%m-%dT%H:%M:%SZ', object_timestamp)
end

-- Helper function to name, url and serializedtags
local function get_tag_quadruple(object)
    local features = {}
    local ser = {}
    local url = nil
    local name = object:grab_tag('name')
    -- Iterate over each tag from the osm object
    for key, value in pairs(object.tags) do
        -- find url or website entry
        if key == 'url' then
            url = object:grab_tag(key)
            goto continue
        elseif key == 'website' then
            url = object:grab_tag(key)
            goto continue
        elseif osm2pgsql.has_suffix(key, ':url') then
            url = object:grab_tag(key)
            goto continue
        elseif osm2pgsql.has_suffix(key, ':website') then
            url = object:grab_tag(key)
            goto continue
        end

        if list_contains(map_features, key) then
            -- osm object.tag is definied as a mapfeature
            table.insert(features, get_classcode(key, value))
            goto continue
        else
            -- osm object.tag is not very relevant,
            -- therefore it is stored in serializedtags table
            ser[key] = value
            goto continue
        end
        ::continue::
    end
    -- If the table is empty, an empty table should not be saved.
    -- Instead, the value is set to nil (PostgreSQL NULL)
    if next(ser) == nil then
        ser = nil
    end

    return name, features, url, ser
end

-- function for all nodes
function osm2pgsql.process_node(object)
    if clean_tags(object.tags) then
        return
    end

    local object_name, object_features, object_url, object_serializedtags = get_tag_quadruple(object)
    tables.nodes:add_row({
        name = object_name,
        url = object_url,
        tstamp = reformat_date(object.timestamp),
        mapfeatures_ids = table.concat(object_features,"; "),
        serializedtags = object_serializedtags,
        geom = { create = 'point' },
        uid = object.uid,
        username = object.user,
        geom_changed = false,
        object_changed = false,
        deleted = false,
        object_new = false,
        has_name = false,
        valid = false
    })
end

-- function for all ways
function osm2pgsql.process_way(object)
    if clean_tags(object.tags) then
        return
    end
    local object_name, object_features, object_url, object_serializedtags = get_tag_quadruple(object)
    tables.ways:add_row({
        name = object_name,
        url = object_url,
        tstamp = reformat_date(object.timestamp),
        mapfeatures_ids = table.concat(object_features,"; "),
        serializedtags = object_serializedtags,
        geom = { create = 'line' },
        uid = object.uid,
        username = object.user,
        geom_changed = false,
        object_changed = false,
        deleted = false,
        object_new = false,
        has_name = false,
        valid = false
    })

    -- for each node id of the way insert an entry to the waynodes table
    for _, id in pairs(object.nodes) do
        tables.waynodes:add_row({
            way_id = object.id,
            node_id = id
        })
    end
end

-- function for all relations
function osm2pgsql.process_relation(object)
    if clean_tags(object.tags) then
        return
    end
    local object_name, object_features, object_url, object_serializedtags = get_tag_quadruple(object)
    tables.relations:add_row({
        name = object_name,
        url = object_url,
        tstamp = reformat_date(object.timestamp),
        mapfeatures_ids = table.concat(object_features,"; "),
        serializedtags = object_serializedtags,
        geom = { create = 'area' },
        uid = object.uid,
        username = object.user,
        geom_changed = false,
        object_changed = false,
        deleted = false,
        object_new = false,
        has_name = false,
        valid = false
    })

    for _, member in ipairs(object.members) do
        -- if type is a node
        if member.type == "n" then
            tables.relationmembers:add_row({
                relation_id = object.id,
                node_id = member.ref,
                way_id = nil,
                member_rel_id = nil,
                role = member.role

            })
        end
        -- if type is a way
        if member.type == "w" then
            tables.relationmembers:add_row({
                relation_id = object.id,
                node_id = nil,
                way_id = member.ref,
                member_rel_id = nil,
                role = member.role

            })
        end
        -- if type is a relation
        if member.type == "r" then
            tables.relationmembers:add_row({
                relation_id = object.id,
                node_id = nil,
                way_id = nil,
                member_rel_id = member.ref,
                role = member.role

            })
        end
    end

end